#---
#apiVersion: secrets.hashicorp.com/v1beta1
#kind: VaultConnection
#metadata:
#  name: dynamic-auth
#  namespace: vault-secrets-operator-system
#spec:
#  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: transit-auth
  # This Vault Auth is used for transit engine hence stays in the VSO namespace
  namespace: vault-secrets-operator-system
#  labels:
#    cacheStorageEncryption: "true"
spec:
  method: kubernetes
  mount: demo-auth-mount
  namespace: us-west-org
  vaultConnectionRef: default #dynamic-auth
  kubernetes:
    role: auth-role-operator
    serviceAccount: demo-operator
    audiences:
      - vault
#  storageEncryption:
#    mount: demo-transit
#    keyName: vso-client-cache
